name: Blog post workflow
on:
  schedule:
    # Runs every day at 00:00 UTC (12am SG)
    - cron: '0 0 * * *

jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://osi.codes/rss.xml
          count: 3
      - name: Commit file changes
        run: \
            git config --global user.name 'vicradon'
            git config --global user.email 'osinachi.chukwujama@gmail.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
